AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  AthenaQueryRequestHandlerFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: java8
      Handler: com.github.therycn.AthenaQueryRequestHandler::handleRequest
      Timeout: 60
      CodeUri: ./target/lambda.jar
